micronaut:
  application:
    name: api
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

vertx:
  mysql:
    client:
      port: 3306
      host: localhost
      database: db
      user: user
      password: password
      maxSize: 5

endpoints:
  health:
    jdbc:
      enabled: true